openapi: 3.0.0
info:
  title: Get Unresolved Topic Count
  version: 1.0.0
paths:
  /categories/{category_id}/unresolved/count:
    get:
      summary: Get the number of unresolved topics in a specific category
      description: Returns the count of unresolved topics within the specified category.
      parameters:
        - name: category_id
          in: path
          required: true
          description: The ID of the category
          schema:
            type: integer
      responses:
        '200':
          description: Successfully retrieved unresolved topic count
          content:
            application/json:
              schema:
                type: object
                properties:
                  cid:
                    type: integer
                    description: Category ID
                  unresolvedTopicCount:
                    type: integer
                    description: Number of unresolved topics
        '400':
          description: Invalid category ID
        '404':
          description: Category not found
